### ISSUE TITLE
Hey Just a Question

### ISSUE THREAD

**Issue by ThelianTech** [TheUnderTaker11/More-Avaritia#10]
Hey I was Wondering if i could take a look over porting the mod to 1.12.2. I've been having a programming itch for a while  and this mod seems simple enough for me to experiment with. If your interested jsut reply back here and let me know.

**Comment by ToMe25** [comment]
@Kronos9247 allready Updated this Mod to 1.12.2, but no one has Uploaded Build on 1.12.2 Curseforge.

**Comment by zyojv** [comment]
I am going to upload the 1.12.2 build today.
