### ISSUE TITLE
Item request

### ISSUE THREAD

**Issue by VirusXD142** [TheUnderTaker11/More-Avaritia#2]
It will be nice if you can add some Creative item:
IC2  and Advance Solar panel quantum Gererator
Mekanisen Creative Gastanks tanks and for
Techreborn 
Creative solar and Simpeljetpacks Creative Jetpacks. 
Extra Utilities 2 Creative Builderwand 
Extreme Reactors Creative Coolenport and Turbine Creative Steam Generator
Steave's Cards2 Creative Hull and Upgrades

If something is misspelled my english is not so good and I hope you could understand everything
 I hope it is in the right theme

**Comment by TheUnderTaker11** [comment]
The creative builders wand will not be added, but everything else looks like it will work. I'll get on this.

**Comment by TheUnderTaker11** [comment]
Everything I'm going to add from this list has been added, will close when the new file is up.
