### ISSUE TITLE
Violent CRASH!!!

### ISSUE THREAD

**Issue by Gysburi** [TheUnderTaker11/More-Avaritia#20]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
  CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.5.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 12/23/18 8:54 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from More Avaritia (moreavaritia)
Caused by: java.lang.RuntimeException: Invalid shaped ore recipe: false, BIIIBIIIB, IQIICIIQI, IIQZZZQII, IIZQBQZII, BCZBEBZCB, IIZQBQZII, IIQZZZQII, IQIICIIQI, BIIIBIIIB, E, 1xitem.singularity@11, I, 1xtile.air@6, Q, 1xtile.air@5, C, null, B, 1xtile.avaritia:block_resource@1, Z, null, 
	at net.minecraftforge.common.crafting.CraftingHelper.parseShaped(CraftingHelper.java:346)
	at com.theundertaker11.moreavaritia.RecipeUtil.addRecipe(RecipeUtil.java:20)
	at com.theundertaker11.moreavaritia.compat.quantumflux.QuantumFluxRecipes.init(QuantumFluxRecipes.java:25)
	at com.theundertaker11.moreavaritia.compat.CompatMain.init(CompatMain.java:92)
	at com.theundertaker11.moreavaritia.MoreAvaritiaMain.init(MoreAvaritiaMain.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1686297536 bytes (1608 MB) / 2457985024 bytes (2344 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                      | Source                                             | Signature                                |
	|:----- |:------------------------- |:---------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                 | 1.12.2                       | minecraft.jar                                      | None                                     |
	| LCHI  | mcp                       | 9.42                         | minecraft.jar                                      | None                                     |
	| LCHI  | FML                       | 8.0.99.99                    | forge-1.12.2-14.23.5.2796.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                     | 14.23.5.2796                 | forge-1.12.2-14.23.5.2796.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | unicodefontextensioncore  | 1.12.2-2.6                   | minecraft.jar                                      | None                                     |
	| LCHI  | lesslag                   | 1.0                          | minecraft.jar                                      | None                                     |
	| LCHI  | openmodscore              | 0.12.1                       | minecraft.jar                                      | None                                     |
	| LCHI  | foamfixcore               | 7.7.4                        | minecraft.jar                                      | None                                     |
	| LCHI  | dsurroundcore             |                              | minecraft.jar                                      | None                                     |
	| LCHI  | unicodefontextension      | 1.12.2-2.7                   | UnicodeFontExtension-1.12.2-2.7.jar                | None                                     |
	| LCHI  | deconstruction            | 3.0.4                        | [MC1.12.2]DeconTable-3.0.4.jar                     | None                                     |
	| LCHI  | baubles                   | 1.5.2                        | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHI  | jei                       | 4.13.1.225                   | jei_1.12.2-4.13.1.225.jar                          | None                                     |
	| LCHI  | botania                   | r1.10-358                    | Botania+r1.10-358.jar                              | None                                     |
	| LCHI  | mantle                    | 1.12-1.3.3.39                | Mantle-1.12-1.3.3.39.jar                           | None                                     |
	| LCHI  | tconstruct                | 1.12.2-2.11.0.106            | TConstruct-1.12.2-2.11.0.106.jar                   | None                                     |
	| LCHI  | conarm                    | 1.2.1                        | conarm-1.12.2-1.2.1.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHI  | codechickenlib            | 3.2.2.353                    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | avaritia                  | 3.3.0                        | Avaritia-1.12.2-3.3.0.28-universal.jar             | None                                     |
	| LCHI  | redstoneflux              | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHI  | brandonscore              | 2.4.9                        | BrandonsCore-1.12.2-2.4.9.195-universal.jar        | None                                     |
	| LCHI  | draconicevolution         | 2.3.18                       | Draconic-Evolution-1.12.2-2.3.18.329-universal.jar | None                                     |
	| LCHI  | plustic                   | 6.5.4.2                      | plustic-6.5.4.2.jar                                | None                                     |
	| LCHI  | armoryexpansion           | 0.2.0                        | armoryexpansion-0.2.0.jar                          | None                                     |
	| LCHI  | avaritiatweaks            | 1.12.2-1.1                   | AvaritiaTweaks-1.12.2-1.1.jar                      | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHI  | bdlib                     | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| LCHI  | forestry                  | 5.8.2.375                    | forestry_1.12.2-5.8.2.375.jar                      | None                                     |
	| LCHI  | beebetteratbees           | 2.0.3                        | beebetteratbees-1.12.2-2.0.3.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHI  | bettermobgriefinggamerule | 1.12.2-7.0.1                 | bettermobgriefinggamerule-1.12.2-7.0.1.jar         | None                                     |
	| LCHI  | careerbees                | 1.0                          | careerbees-0.4.0.jar                               | None                                     |
	| LCHI  | chameleon                 | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHI  | chickenchunks             | 2.4.1.73                     | ChickenChunks-1.12.2-2.4.1.73-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | claybucket                | 1.1                          | ClayBucket-1.12-1.1.jar                            | None                                     |
	| LCHI  | clumps                    | 3.1.1                        | Clumps-3.1.1.jar                                   | None                                     |
	| LCHI  | storagedrawers            | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| LCHI  | compactdrawers            | 1.12.2-1.0.3.98              | CompactDrawers-1.12.2-1.0.3.98.jar                 | None                                     |
	| LCHI  | controlledburn            | 1.12.2.011                   | Controlled+Burn-1.12.2.011.jar                     | None                                     |
	| LCHI  | craftingtweaks            | 8.1.9                        | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
	| LCHI  | cucumber                  | 1.1.3                        | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LCHI  | enchanting_tweaks         | 1.1.1                        | enchanting_tweaks-1.1.1.jar                        | None                                     |
	| LCHI  | enderstorage              | 2.4.5.135                    | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | exnihilocreatio           | 1.12-0.2.4                   | exnihilocreatio-1.12-0.2.4.jar                     | None                                     |
	| LCHI  | excompressum              | 3.0.26                       | ExCompressum_1.12.2-3.0.26.jar                     | None                                     |
	| LCHI  | theoneprobe               | 1.4.25                       | theoneprobe-1.12-1.4.25.jar                        | None                                     |
	| LCHI  | extrabotany               | 48                           | ExtraBotany-r1.1-49.jar                            | None                                     |
	| LCHI  | foamfix                   | 0.10.3-1.12.2                | foamfix-0.10.3-1.12.2.jar                          | None                                     |
	| LCHI  | forgelin                  | 1.8.2                        | Forgelin-1.8.2.jar                                 | None                                     |
	| LCHI  | forgemultipartcbe         | 2.6.0.79                     | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | microblockcbe             | 2.6.0.79                     | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | None                                     |
	| LCHI  | minecraftmultipartcbe     | 2.6.0.79                     | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | None                                     |
	| LCHI  | cfm                       | 6.2.0                        | furniture-6.2.0-1.12.2.jar                         | None                                     |
	| LCHI  | gendustry                 | 1.6.5.8                      | gendustry-1.6.5.8-mc1.12.2.jar                     | None                                     |
	| LCHI  | gendustryjei              | 1.0.2                        | gendustryjei-1.0.2.jar                             | None                                     |
	| LCHI  | lunatriuscore             | 1.2.0.42                     | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
	| LCHI  | ingameinfoxml             | 2.8.2.94                     | InGameInfoXML-1.12.2-2.8.2.94-universal.jar        | None                                     |
	| LCHI  | inventorytweaks           | 1.64-dev+release.117.7221546 | InventoryTweaks-1.64-dev.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHI  | ironjetpacks              | 1.0.5                        | ironjetpacks-1.12-1.0.5.jar                        | None                                     |
	| LCHI  | jeibees                   | 0.9.0.5                      | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
	| LCHI  | jeresources               | 0.8.5.27                     | JustEnoughResources-1.12.2-0.8.5.27.jar            | None                                     |
	| LCHI  | magicbees                 | 1.0                          | MagicBees-1.12.2-3.1.10.jar                        | None                                     |
	| LCHI  | mcjtylib_ng               | 3.0.6                        | mcjtylib-1.12-3.0.6.jar                            | None                                     |
	| LCHE  | moreavaritia              | 2.4                          | moreavaritia-mc1.12.2-2.4.jar                      | None                                     |
	| LCH   | morebees                  | 1.12.2-2.0.1                 | morebees-1.12.2-2.0.1.jar                          | None                                     |
	| LCH   | nolives                   | 1.2.2                        | nolives-1.12.2-1.2.2.jar                           | None                                     |
	| LCH   | recipehandler             | 0.12                         | NoMoreRecipeConflict-0.12(1.12.2).jar              | None                                     |
	| LCH   | notenoughwands            | 1.7.1                        | notenoughwands-1.12-1.7.1.jar                      | None                                     |
	| LCH   | openmods                  | 0.12.1                       | OpenModsLib-1.12.2-0.12.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | openblocks                | 1.8                          | OpenBlocks-1.12.2-1.8.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | reborncore                | 3.12.1.385                   | RebornCore-1.12.2-3.12.1.385-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | quantumstorage            | 4.6.4                        | QuantumStorage-1.12-4.6.4.jar                      | None                                     |
	| LCH   | refinedstorage            | 1.6.12                       | refinedstorage-1.6.12.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | rebornstorage             | 1.0.0                        | RebornStorage-1.12.2-3.3.2.79.jar                  | None                                     |
	| LCH   | refined_avaritia          | 2.4                          | refined_avaritia-1.12.2-2.4.jar                    | None                                     |
	| LCH   | refinedstorageaddons      | 0.4.1                        | refinedstorageaddons-0.4.1.jar                     | None                                     |
	| LCH   | simplemagnet              | 1.12.0-1.2.6                 | simplemagnet-1.12.2-1.2.11.jar                     | None                                     |
	| LCH   | simplesolarpanels         | 1.2.0                        | SimpleSolarPanels-1.2+1.12.2.jar                   | None                                     |
	| LCH   | supersoundmuffler         | 1.0.2.9                      | supersoundmuffler-1.12.1-1.0.2.9.jar               | None                                     |
	| LCH   | tcomplement               | ${version}                   | TinkersComplement-1.12.2-0.2.3b.jar                | None                                     |
	| LCH   | tinkersjei                | 1.0                          | tinkersjei-1.0.jar                                 | None                                     |
	| LCH   | tinkertoolleveling        | 1.12.2-1.1.0.DEV.b23e769     | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCH   | tooltweaks                | 1.0.7                        | tooltweaks-1.0.7.jar                               | 291a6dbeba80e50ca46c28c20d934b08a84efc8d |
	| LCH   | topaddons                 | 1.12.2-1.10.1                | topaddons-1.12.2-1.10.1.jar                        | None                                     |
	| LCH   | torchmaster               | 1.6.4.62                     | torchmaster_1.12.2-1.6.4.62.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCH   | translocators             | 2.5.1.77                     | Translocators-1.12.2-2.5.1.77-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | treechopper               | 1.2.4                        | TreeChopper-1.12.2-1.2.4.jar                       | None                                     |
	| LCH   | treegrowingsimulator      | 0.0.4                        | TreeGrowingSimulator2017-1.0.1.jar                 | None                                     |
	| LCH   | voidislandcontrol         | 1.5.1                        | voidislandcontrol-1.5.1.jar                        | None                                     |
	| LCH   | wrcbe                     | 2.3.1                        | WR-CBE-1.12.2-2.3.1.30-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | dsurround                 | 3.4.10.5                     | DynamicSurroundings-1.12.2-3.4.10.5.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | presets                   | 3.4.10.5                     | DynamicSurroundings-1.12.2-3.4.10.5.jar            | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
  
CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
  bre.ufex.asm.Transformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.5.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.35' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- ExNihiloPlugin (Enabled/Not Forced)

	List of loaded APIs: 
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* BotaniaAPI (92) from Botania+r1.10-358.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.12.2-8.1.9.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.18.329-universal.jar
		* ExCompressum|API (1.0) from ExCompressum_1.12.2-3.0.26.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.375.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.375.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.13.1.225.jar
		* openblocks|api (1.2) from OpenBlocks-1.12.2-1.8.jar
		* reborncoreAPI (3.12.1.385) from RebornCore-1.12.2-3.12.1.385-universal.jar
		* reborncoreAPI|Power (3.12.1.385) from RebornCore-1.12.2-3.12.1.385-universal.jar
		* reborncoreAPI|Recipe (3.12.1.385) from RebornCore-1.12.2-3.12.1.385-universal.jar
		* reborncoreAPI|Tile (3.12.1.385) from RebornCore-1.12.2-3.12.1.385-universal.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.25.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.12.1.385
		Runtime Debofucsation 1
		RenderEngine: 0

**Comment by zyojv** [comment]
Try to disable QuantumFlux in the config of more avaritia
