### ISSUE TITLE
crash when installed in version 1.12.2

### ISSUE THREAD

**Issue by Edwinchen1** [TheUnderTaker11/More-Avaritia#21]
here is the crash report.
https://paste.ubuntu.com/p/3T2zzJgR8t/

it says something is wrong with a ore crafting recipe. but excuse me? using the extreme crating to craft an ore????? did i misread anything or it's just what it is?

byw, if anyone would have a solution for this(of course not "don't install this mod"), i would really appreciate it.

**Comment by TheUnderTaker11** [comment]
To clarify, when it say an ore recipe it doesn't mean a recipe for an ore, it's just a term they use for OreDictonary recipes and such.
Secondly, the problem comes somewhere from the list of QuantumFlux recipes, try installing QuantumFlux and see if that fixes the problem until the code is fixed.

**Comment by TheUnderTaker11** [comment]
I actually found and probably fixed the problem, if @Kronos9247 could compile that small change and upload real quick that SHOULD fix your problem for sure @Edwinchen1, I'll try and set up my workspace to compile it later, it just takes quite a bit of time to install all the mods into the workspace lol.

EDIT: @Edwinchen1 I also jsut tested myself and was able to run MoreAvaritia just fine with QuantumFlux installed, so I'm almost 100% sure that fix I made will solve your problem, and that a temp fix is just to install quantumflux.

**Comment by TheUnderTaker11** [comment]
Much easier to do now, compiled and uploaded fix. Also fixed a sort of related problem where @Kronos9247 didn't change the mod ID's to lowercase as must be done in 1.11 onward.
