### ISSUE TITLE
Creative Mana Tablet 

### ISSUE THREAD

**Issue by jefferyrlc** [TheUnderTaker11/More-Avaritia#24]
So the recipe for the Creative Mana Tablet from Botania is uncraftable. Not that there isn't a recipe for it, but the recipe is impossible as you cannot have multiple Eye of the Flugel. Botania has limited the player to only obtaining one aesir relic ever from the Dice of Fate.

Minecraft: 1,12.2
Forge: 14.23.5.2815
Avaritia: 3.3.0
Botania: r1.10-360
More Avaritia: 2.41

**Comment by TheUnderTaker11** [comment]
Update the mod it's already been fixed 3 days ago (I realized that fact myself while updating), you just are not on the latest version.
