### ISSUE TITLE
Infinity-1 Pick hand sprite is held as an item instead of a tool

### ISSUE THREAD

**Issue by tacct6** [TheUnderTaker11/More-Avaritia#29]
version 3.2, only a visual issue, but this is how the Infinity-1 Pick appears when being held:
![image](https://user-images.githubusercontent.com/39307411/55282122-e0a27680-530b-11e9-9ff8-ef3301424873.png)

![image](https://user-images.githubusercontent.com/39307411/55282126-ff087200-530b-11e9-815f-e6a939f0af6a.png)

**Comment by TheUnderTaker11** [comment]
Yea i realized this and it's fixed, just haven't done enough other stuff to
be worth pushing an update.

**Comment by TheUnderTaker11** [comment]
I'm like 80% sure this got fixed back in a late 2020 release.
