### ISSUE TITLE
creative dank null

### ISSUE THREAD

**Issue by blackdragonIV** [TheUnderTaker11/More-Avaritia#31]
maybe a recipe for the creative dank null would be neat

**Comment by TheUnderTaker11** [comment]
Your wish has been granted once release v1.5 is on Curseforge.
![image](https://user-images.githubusercontent.com/16872377/198890120-306a1021-03b8-40f9-93bb-a57a2899d7d4.png)

**Comment by TheUnderTaker11** [comment]
v1.5 uploaded, should be approved and available shortly.
