### ISSUE TITLE
Infinity Catalyst Added Items not showing up.

### ISSUE THREAD

**Issue by Psimekai** [TheUnderTaker11/More-Avaritia#34]
First, thank you for the great mod. Modders make Minecraft the magical phenomenon that it is.

I just installed More Avaritia, and while the new creative item recipes are loaded, the Infinity Catalyst recipe remains unchanged. I believe, based on your documentation, that some other items are to be added if the related mod is installed?

For example, I have Draconic Evolution installed, but no core is added to the Catalyst recipe that I can see. I have not touched the config file, and it shows Draconic Evolution and others to be active, but my Infinity Catalyst recipe is no different than before.

**Comment by TheUnderTaker11** [comment]
That was a problem with the fact they changed how shine catalyst items
works and I haven't went in and figured out the new way yet.

**Comment by Psimekai** [comment]
I see. No worries. Just wanted to inform you incase you didn't already know, but clearly, you do. 

Thanks again for the great mod!

**Comment by TheUnderTaker11** [comment]
This will be fixed in the v1.5 release I'm putting out at some point today.
Only took over 3 years to fix, no big deal lol.

![image](https://user-images.githubusercontent.com/16872377/198888588-a083345d-622d-485e-8d4d-ab28a528413b.png)

**Comment by TheUnderTaker11** [comment]
v1.5 uploaded, should be approved and available shortly.
