### ISSUE TITLE
[Suggestion] Enable/Disable items in Infinity Catalyst recipe

### ISSUE THREAD

**Issue by Psychomaniac14** [TheUnderTaker11/More-Avaritia#37]
So I'm making a modpack and I was doing everything that I wanted with it adding mods and adding EMC to items and after I had added an EMC value to all the Avaritia items and Creative items I added Applied Energistics 2, which added the 64k ME Storage Component to the Infinity Catalyst recipe. Now since I didn't want to have to redo all those recipes and I don't know how to change the recipe I decided to come here to request some configurable options for adding and removing items from the Infinity Catalyst recipe. Of course I would also like the amount of that item in the recipe to be configurable (1-4 I say would be a reasonable limit) so that if the change is made, I could still easily have 2 blocks of enderium in the recipe. I hope I'm not asking for too much :)

**Comment by TheUnderTaker11** [comment]
Well if you had looked in the config you would see that each item can be
disabled from the infinity catalyst recipe. And on top of that each
individual recipe along with each mod as a whole can be disabled.

**Comment by Psychomaniac14** [comment]
![javaw 2019-07-22 07-17-19-549](https://user-images.githubusercontent.com/53139082/61597200-c987eb80-ac50-11e9-936c-b3caf92d8f79.jpg)

**Comment by Psychomaniac14** [comment]
I was using version 2.4 of the mod
oops XD

**Comment by Psychomaniac14** [comment]
also the config option doesn't appear in-game

**Comment by TheUnderTaker11** [comment]
You need to edit the config file, if you don't know where that is a quick
google search will help you figure it out.

**Comment by Psychomaniac14** [comment]
I found it

**Comment by Psychomaniac14** [comment]
btw in the suggestion I also said that you should be able to add items to the recipe

**Comment by TheUnderTaker11** [comment]
I don't think having the ability to add new items to the recipe is worth adding to this mod. Avaritia already has crafttweaker support for any modpack devs who would want to do that themselves.
