### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by PurplePaolo** [TheUnderTaker11/More-Avaritia#38]
why dont you remove he creative tab of moreavaritia? it has no items in it

**Comment by TheUnderTaker11** [comment]
Are you using the latest version? It should have the infinity -1 pick and
hoe in it if nothing else

**Comment by PurplePaolo** [comment]
yes i am using that version and they are in the avaritia 1.1x mod tab

**Comment by TheUnderTaker11** [comment]
Hm alright I'll look into it when I get time. I added it cause in the long
run I plan on having more items, but in the meantime might remove it.
