### ISSUE TITLE
Small Mistake On Regist Name

### ISSUE THREAD

**Issue by thought0901** [TheUnderTaker11/More-Avaritia#42]
![](https://user-images.githubusercontent.com/84757717/198643337-c28324a5-06d3-4efb-81c3-610acb8f0e42.png)

The name 'mineaft:stone' should be 'minecraft:stone'

**Comment by TheUnderTaker11** [comment]
It's a super expensive recipe for dirt, so not that big of a deal lol. Not any special dirt, just minecraft:dirt.

Probably put it there when I was testing the JSON recipe format to transition recipes to.

Either way, fixed it in the code for if I ever release another file any time soon.

**Comment by TheUnderTaker11** [comment]
To answer the when question, I have just released v1.5 which fixes this bug and #34 , code has just been updated to github
