### ISSUE TITLE
little fruitful idea

### ISSUE THREAD

**Issue by higakoryu** [TheUnderTaker11/More-Avaritia#6]
can you add a creative thaumcraft jar which has infinite essentia?And also a bow that does infinite damage like the sword of the cosmos please? And what about a faster neutron collector?Also what about recipes for the creative flux pack and jetpack(a jetplate would also be nice) from simply jetpack?Please make mob killed by the creative spike drop items

**Comment by Morpheus1101** [comment]
Take a look at what is planned for 1.13//1.14 on the avaritia Discord as quite a few of these suggestions are all ready planned

If the cosmic bow dosent 1 shot mobs, then i will have to look into that as i agree that it should kill instantly the same way the sword does.

**Comment by TheUnderTaker11** [comment]
All of these are either added, will be added, or can't/won't be added (Such as changing creative spikes, which come from a completely different mod.)      
Seems like Morpheus plans on adding something related to Thaumcraft as well.

So closing this suggestion.
