### ISSUE TITLE
Dev

### ISSUE THREAD

**Issue by zyojv** [TheUnderTaker11/More-Avaritia#7]
I would like to take over development on More Avaritia.

**Comment by TheUnderTaker11** [comment]
Not gonna lie I saw this then completely forgot about it till today, but yea feel free to take over. I'm not 100% sure my Github code is fully up to date, so if you want just email me at cabmanbellou@gmail.com and I will reply with a .rar containing my src file I keep a backup of.

Send me a working updated version and I will give you the ability to upload things both here and to the cursepage.
